### ISSUE TITLE
Missing register states when referring to a variable after a return

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#501]
Original GitLab issue: https://gitlab.com/inko-lang/inko/-/issues/292

---

This snippet:

```inko
class async Main {
  fn async main {
    let mut i = 0

    return

    while i < 100 { i += 1 }
  }
}
```

Results in this compiler error when running Inko in debug mode:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `/home/yorickpeterse/Projects/inko/inko/target/debug/inko run /home/yorickpeterse/Downloads/test.inko`
thread 'main' panicked at 'missing state for register r2 in block b2 (method "main" in "/home/yorickpeterse/Downloads/test.inko")', compiler/src/mir/passes.rs:4208:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: compiler::mir::passes::LowerMethod::register_state
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:4208:9
   3: compiler::mir::passes::LowerMethod::register_is_available
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:4110:9
   4: compiler::mir::passes::LowerMethod::check_if_moved
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:3487:12
   5: compiler::mir::passes::LowerMethod::identifier
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:3035:17
   6: compiler::mir::passes::LowerMethod::expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1367:50
   7: compiler::mir::passes::LowerMethod::call
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1715:25
   8: compiler::mir::passes::LowerMethod::expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1360:41
   9: compiler::mir::passes::LowerMethod::input_expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1863:19
  10: compiler::mir::passes::LowerMethod::match_expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:2395:25
  11: compiler::mir::passes::LowerMethod::expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1372:42
  12: compiler::mir::passes::LowerMethod::loop_expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1471:13
  13: compiler::mir::passes::LowerMethod::expression
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1371:41
  14: compiler::mir::passes::LowerMethod::lower_method_body
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1219:17
  15: compiler::mir::passes::LowerMethod::run
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1172:9
  16: compiler::mir::passes::LowerToMir::define_async_method
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:1015:9
  17: compiler::mir::passes::LowerToMir::define_class
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:932:34
  18: compiler::mir::passes::LowerToMir::lower_types
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:834:21
  19: compiler::mir::passes::LowerToMir::run_all
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/mir/passes.rs:813:13
  20: compiler::compiler::Compiler::lower_to_mir
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/compiler.rs:197:16
  21: compiler::compiler::Compiler::compile_to_mir
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/compiler.rs:145:9
  22: compiler::compiler::Compiler::compile_bytecode
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/compiler.rs:125:9
  23: compiler::compiler::Compiler::compile_to_memory
             at /home/yorickpeterse/Projects/inko/inko/compiler/src/compiler.rs:77:20
  24: inko::command::run::run
             at /home/yorickpeterse/Projects/inko/inko/inko/src/command/run.rs:90:18
  25: inko::command::main::run
             at /home/yorickpeterse/Projects/inko/inko/inko/src/command/main.rs:55:24
  26: inko::main
             at /home/yorickpeterse/Projects/inko/inko/inko/src/main.rs:17:11
  27: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

At this point I think this `debug_assert` should become a regular assert, otherwise you may get a segmentation fault in a release build. In addition, this bug has happened before so maybe it's time for a proper long term solution.

As for this particular case: we should probably just not bother to lower to MIR when the code is obviously unreachable. This may hide certain errors (e.g. variables being used after moves), but since the code is unreachable that doesn't matter.

**Comment by yorickpeterse** [comment]
The example in the issue description no longer triggers this error, but I'm sure I've run into it recently, so I'll need to find another way to reproduce the problem.

**Comment by yorickpeterse** [comment]
Oops, I forgot: we're using a `debug_assert` and I was using a binary built in release mode, so the panic never triggered. This is still an issue after all.
