### ISSUE TITLE
Version 0.17.0 LLVM compile failure

### ISSUE THREAD

**Issue by KieranP** [inko-lang/inko#774]
### Please describe the bug

Getting this error when trying to build codebase under 0.17.0

Repo: https://github.com/KieranP/Game-Of-Life-Implementations/tree/master/inko

```
RUST_BACKTRACE=full inko build -i . -o play play.inko
thread '<unnamed>' panicked at compiler/src/llvm/passes.rs:1689:35:
index out of bounds: the len is 808 but the index is 18446744073709551615
stack backtrace:
   0:        0x107ea0e78 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h192489893ab3de20
   1:        0x107eb8968 - core::fmt::write::h2573968dce8b4c8e
   2:        0x107ea0c48 - std::io::Write::write_fmt::hd688b4e0e14280fb
   3:        0x107e94598 - std::panicking::default_hook::{{closure}}::h132ab4fd80cbd688
   4:        0x107e940e0 - std::panicking::default_hook::h25db1205ededf4a8
   5:        0x107e94b1c - std::panicking::rust_panic_with_hook::h1a5e700ba9552453
   6:        0x107ea13b8 - std::panicking::begin_panic_handler::{{closure}}::h4b087c40eb4a42d9
   7:        0x107ea10d0 - std::sys::backtrace::__rust_end_short_backtrace::heff777664c13f8e2
   8:        0x107e94708 - _rust_begin_unwind
   9:        0x108173e4c - core::panicking::panic_fmt::h681f622c7f427738
  10:        0x108173f80 - core::panicking::panic_bounds_check::h645582215ea94a7f
  11:        0x10422732c - compiler::llvm::passes::LowerMethod::instruction::hef70c9488b3adc04
  12:        0x10421eef4 - compiler::llvm::passes::LowerMethod::method_body::hd422b346cd52030a
  13:        0x10421aed4 - compiler::llvm::passes::Worker::run::hac9f63ee2725bbdc
  14:        0x10429243c - std::sys::backtrace::__rust_begin_short_backtrace::h993ad168051894fa
  15:        0x104281c44 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0fce2d2ae0ed45d3
  16:        0x107e7ac84 - std::sys::pal::unix::thread::Thread::new::thread_start::h9e79a8d54639c27f
  17:        0x19912b2e4 - __pthread_deallocate
zsh: abort      RUST_BACKTRACE=full inko build -i . -o play play.inko
```

### Operating system

macOS

### Inko version

0.17.0

**Comment by yorickpeterse** [comment]
@KieranP What version of LLVM are you using?

**Comment by yorickpeterse** [comment]
Having just tried it, I'm getting the same error using LLVM 17, so I don't think the LLVM version is to blame here.

**Comment by yorickpeterse** [comment]
Note to self: using a debug build of Inko instead produces the following error:

```
RUST_BACKTRACE=1 ~/Projects/inko/inko/target/debug/inko build -i . -o play play.inko
thread 'main' panicked at compiler/src/mir/mod.rs:201:9:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
   3: <compiler::mir::BlockId as core::ops::arith::SubAssign<usize>>::sub_assign
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/mir/mod.rs:201:9
   4: compiler::mir::Method::remove_unreachable_blocks::{{closure}}
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/mir/mod.rs:1890:54
   5: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/slice/iter/macros.rs:254:21
   6: compiler::mir::Method::remove_unreachable_blocks
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/mir/mod.rs:1890:13
   7: compiler::mir::Mir::remove_unreachable_blocks
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/mir/mod.rs:2121:13
   8: compiler::mir::Mir::simplify_graph
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/mir/mod.rs:2302:9
   9: compiler::compiler::Compiler::optimise_mir
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/compiler.rs:535:13
  10: compiler::compiler::Compiler::build
             at /var/home/yorickpeterse/Projects/inko/inko/compiler/src/compiler.rs:257:9
  11: inko::command::build::run
             at /var/home/yorickpeterse/Projects/inko/inko/inko/src/command/build.rs:223:18
  12: inko::command::main::run
             at /var/home/yorickpeterse/Projects/inko/inko/inko/src/command/main.rs:60:26
  13: inko::main
             at /var/home/yorickpeterse/Projects/inko/inko/inko/src/main.rs:13:11
  14: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Using `--opt=none` doesn't trigger this. I strongly suspect that the way we shift block IDs in `Method.remove_unreachable_blocks` is broken, resulting to the out of bounds errors in the LLVM stage.

**Comment by KieranP** [comment]
@yorickpeterse I'm using the version Mac Sequoia provides by default:

```
> llvm-g++ --version
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by yorickpeterse** [comment]
Since 0.18.0 is probably 2-3 months away, I'll publish the fix as 0.17.1 in the next few hours.

**Comment by yorickpeterse** [comment]
@KieranP The fix is published as part of 0.17.1. It may take a day or so before it becomes available in Homebrew.

**Comment by KieranP** [comment]
@yorickpeterse Thanks. Can confirm all is working again.

**Comment by PLC-Programmer** [comment]
Re "Using --opt=none doesn't trigger this." 

I need this switch to build something successfully with **inko 0.18.1**:
$ inko build hello_world.inko
thread '<unnamed>' panicked at compiler/src/llvm/passes.rs:566:65:
called `Result::unwrap()` on an `Err` value: "invalid PostOrderFunctionAttrs pass parameter \'skip-non-recursive\' "
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' panicked at compiler/src/llvm/passes.rs:566:65:
called `Result::unwrap()` on an `Err` value: "invalid PostOrderFunctionAttrs pass parameter \'skip-non-recursive\' "
Aborted (core dumped)

Now building like this:
$ inko build hello_world.inko **--opt=none**
$ ./build/none/hello_world
Hello, world!
$

My OS is: Linux ... 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

At first I thought my LLVM is broken. It's not apparently. But thank you very much for this tip. I'll try it with more than a "Hello, world!" app in Inko:

_import std.stdio (Stdout)

type async Main {
  fn async main {
    Stdout.new.print('Hello, world!')
  }
}_

**Comment by yorickpeterse** [comment]
@PLC-Programmer Your problem isn't related to this issue at all, it's because of https://github.com/inko-lang/inko/issues/816. That issue is resolved in `main`, so your best bet is to build from source until a new release is available.
